=== Pablomp94/html1/EXAMEN/formula1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

        <xs:simpleType name="resEdad">
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="18"/>
            <xs:maxInclusive value="40"/>
          </xs:restriction>     
        </xs:simpleType>
        
        
        <xs:simpleType name="tcarrera">
          <xs:restriction base="xs:string">
          <xs:pattern value="Monza | Monaco | Silverstone | Nurburgring"/>
          </xs:restriction>
        </xs:simpleType>
        
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="edad" type="resEdad"/>
        <xs:element name="carrera" type="tcarrera"/>
        <xs:element name="hombre"/>
        <xs:element name="mujer"/> 
        <xs:attribute name="altura" type="xs:float"/>
        <xs:attribute name="peso" type="xs:integer"/>
        <xs:attribute name="titulos" type="xs:integer"/>

        <xs:element name="f1">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="piloto" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>      

      <xs:element name="piloto">
        <xs:complexType>
            <xs:sequence> 
              <xs:element ref="nombre"/>
              <xs:element ref="apellidos"/>
              <xs:element ref="edad"/>
              <xs:element ref="escuderia"/>
              <xs:element ref="competicion" minOccurs="0"/>
              <xs:choice>
                  <xs:element ref="hombre"/>
                  <xs:element ref="mujer"/>
              </xs:choice>
           </xs:sequence>
          <xs:attribute ref="altura"/>
          <xs:attribute ref="peso"/>
        </xs:complexType>
    </xs:element>
       
      <xs:element name="competicion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="carrera" maxOccurs="4"/>
            </xs:sequence>
          </xs:complexType>
      </xs:element>     
      
    <xs:element name="escuderia">
      <xs:complexType>
        <xs:simpleContent>
          <xs:extension base="xs:string">
            <xs:attribute ref="titulos"/>        
          </xs:extension>
        </xs:simpleContent>
      </xs:complexType>    
    </xs:element>
      

  
</xs:schema>

=== Pablomp94/html1/EXAMEN/formula1.xml
<?xml version="1.0" encoding="UTF-8"?>
<f1  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="formula1.xsd">
<piloto altura="1.71" peso="70">
<nombre>Carlos</nombre>
<apellidos>Sainz</apellidos>
<edad>29</edad>
<escuderia titulos="20">Ferrari</escuderia>
<competicion>
<carrera>Monaco</carrera>
<carrera>Monza</carrera>
</competicion>
<hombre/>
</piloto>
<piloto altura="1.68" peso="51">
<nombre>Patricia</nombre>
<apellidos>Jordan</apellidos>
<edad>28</edad>
<escuderia titulos="2">Williams</escuderia>
<mujer/>
</piloto>
<piloto altura="1.75" peso="55">
<nombre>Max</nombre>
<apellidos>Verstapen</apellidos>
<edad>22</edad>
<escuderia titulos="6">Red Bull Racing</escuderia>
<competicion>
<carrera>Monaco</carrera>
<carrera>Monza</carrera>
<carrera>Silverstone</carrera>
</competicion>
<hombre/>
</piloto>
<piloto altura="1.86" peso="73">
<nombre>Esteban</nombre>
<apellidos>Ocon</apellidos>
<edad>28</edad>
<escuderia titulos="0">Alpine</escuderia>
<competicion>
<carrera>Monaco</carrera>
<carrera>Monza</carrera>
<carrera>Silverstone</carrera>
<carrera>Nurburgring</carrera>
</competicion>
<hombre/>
</piloto>
<piloto altura="1.78" peso="65">
<nombre>Fernando</nombre>
<apellidos>Alonso</apellidos>
<edad>40</edad>
<escuderia titulos="0">Aston Martin</escuderia>
<competicion>
<carrera>Monaco</carrera>
<carrera>Monza</carrera>
<carrera>Silverstone</carrera>
<carrera>Nurburgring</carrera>
</competicion>
<hombre/>
</piloto>
<piloto altura="1.81" peso="73">
<nombre>Lewis</nombre>
<apellidos>Hamilton</apellidos>
<edad>34</edad>
<escuderia titulos="12">Mercedes</escuderia>
<competicion>
<carrera>Monaco</carrera>
<carrera>Monza</carrera>
<carrera>Silverstone</carrera>
<carrera>Nurburgring</carrera>
</competicion>
<hombre/>
</piloto>
</f1>
